hardware = "ansi"
corpus = "en"
layouts_memory_size = 100
objective = "oxeylyzer"

# If true, use oxeylyzer's definition for all metrics that have an oxeylyzer equivalent.
# Where the definitions differ, it is primarily because (i think) the new definition
# more accurately captures the intent of the metric described in the Keyboard layouts doc.
oxey_mode = true
