# Tuning runs for genetic algorithm
output = './optimizers/logs/annealing_tuning_runs.csv'
log_hamming_clusters = true

[default]
solver = 'annealing'
hardware = 'ortho'
corpus = 'en'
iterations = 500
population = 1000
objective = 'default'

name_format = '{p0}_{pf}_x{annealing_iterations}'
annealing_iterations = 10
p0 = 0.9
pf = 0.01

[[runs]]
p0 = 0.3

[[runs]]
p0 = 0.4

[[runs]]
p0 = 0.5

[[runs]]
p0 = 0.6

[[runs]]
p0 = 0.7

[[runs]]
p0 = 0.8

[[runs]]
p0 = 0.9

[[runs]]
p0 = 0.9
pf = 0.001

[[runs]]
annealing_iterations = 20
iterations = 460

[[runs]]
annealing_iterations = 40
iterations = 411

[[runs]]
annealing_iterations = 5
iterations = 534

[[runs]]
annealing_iterations = 3
iterations = 548

