[formula]
sfb = 28.0
sfs = 11.2 # = 0.4 * 28
scissors = 2.5
lsb = 2.0
pinky_ring = 6.0 # 0.2
in_roll = -3.5 # 2.5
out_roll = -2.4
roll3 = -0.9
alt = -0.4
alt_sfs = 0.6
redirect = 5.4
redirect_sfs = 7.2
redirect_bad = 6.9
redirect_bad_sfs = 9.5
