# this is approximately the objective function used in oxeylyzer

# note that not every metric has the same definition. Key differences:
# a) some metrics have slightly different names (in_roll vs inrolls, roll3 vs onehands)
# b) oxeylyzer weights are all positive, and the sign is determined in the code, while
# jalo expects the weights to be negative when they are desirable features 
# (e.g. in_roll, if that's your thing), and positive if they are effort (e.g. sfb)
# c) some metrics are slightly different definitions, such as scissors and lsb;
# where possible, the oxeylyzer definition is available in the metrics.py file,
# and it is simple to compare the definitions in there. To use the oxeylyzer definition,
# set the oxey_mode flag to true in config.toml
# d) missing is fspeed, which in oxeylyzer is a combination of sfb, sfs and single finger
# skipgrams with more than one skipped letter. We approximate it with sfb and sfs as 
# follows:
# oxeylyzer fspeed = (sfb + (dsfb_ratio)sfs + (dsfb_ratio)**2 * s2fs + (dsfb_ratio)**3 * s3fs) * weight
# approximation function = weight * sfb + (weight * dsfb_ratio) * sfs
# e) oxeylyzer includes max_finger_use, which is not available in jalo. We approximate by
# assigning efforts to each finger separately finger_0 ... finger_9
# f) oxeylyzer has a `heatmap`, which is equivalent to `effort` metric in jalo,
# but the values on each position are different, and can be adjusted in keebs/ansi.py

[formula]
sfb = 28.0
sfs = 11.2 # = 0.4 * 28
scissors = 2.5
lsb = 2.0
pinky_ring = 6.0 # 0.2
in_roll = -3.5 # 2.5
out_roll = -2.4
roll3 = -0.9
alt = -0.4
alt_sfs = 0.6
redirect = 5.4
redirect_sfs = 7.2
redirect_bad = 6.9
redirect_bad_sfs = 9.5
effort = 1.7
